CREATE TABLE IF NOT EXISTS report_document (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    source VARCHAR(255) NOT NULL,
    institution VARCHAR(255) NULL,
    publish_date DATE NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS report_chunk (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    report_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    chunk_uid VARCHAR(64) NOT NULL,
    parent_chunk_uid VARCHAR(64) NULL,
    chunk_type VARCHAR(16) NOT NULL DEFAULT 'CHILD',
    section_path VARCHAR(512) NULL,
    chunk_text TEXT NOT NULL,
    token_count INT NULL,
    page_number INT NULL,
    start_paragraph_id INT NULL,
    end_paragraph_id INT NULL,
    start_page_number INT NULL,
    end_page_number INT NULL,
    filter_reason VARCHAR(255) NULL,
    diagnostics TEXT NULL,
    vector_stored BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_report_chunk_report_id FOREIGN KEY (report_id) REFERENCES report_document(id),
    UNIQUE KEY uk_report_chunk_uid (chunk_uid),
    KEY idx_report_chunk_report_id (report_id),
    KEY idx_report_chunk_parent_uid (parent_chunk_uid),
    KEY idx_report_chunk_type (chunk_type),
    KEY idx_report_chunk_page_range (start_page_number, end_page_number),
    KEY idx_report_chunk_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS report_ocr_page (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    report_id BIGINT NOT NULL,
    page_number INT NOT NULL,
    raw_text MEDIUMTEXT NULL,
    cleaned_text MEDIUMTEXT NULL,
    diagnostics TEXT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_report_ocr_page_report_id FOREIGN KEY (report_id) REFERENCES report_document(id),
    UNIQUE KEY uk_report_ocr_page_report_page (report_id, page_number),
    KEY idx_report_ocr_page_report_id (report_id)
);

CREATE TABLE IF NOT EXISTS report_paragraph_atom (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    report_id BIGINT NOT NULL,
    paragraph_id INT NOT NULL,
    page_number INT NULL,
    section_path VARCHAR(512) NULL,
    paragraph_text MEDIUMTEXT NOT NULL,
    token_count INT NULL,
    diagnostics TEXT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_report_paragraph_atom_report_id FOREIGN KEY (report_id) REFERENCES report_document(id),
    UNIQUE KEY uk_report_paragraph_atom_report_paragraph (report_id, paragraph_id),
    KEY idx_report_paragraph_atom_report_id (report_id),
    KEY idx_report_paragraph_atom_page (report_id, page_number)
);

CREATE TABLE IF NOT EXISTS report_chunk_diagnostic (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    report_id BIGINT NOT NULL,
    chunk_uid VARCHAR(64) NULL,
    parent_chunk_uid VARCHAR(64) NULL,
    parent_index INT NULL,
    chunk_index_in_parent INT NULL,
    chunk_type VARCHAR(16) NOT NULL,
    section_path VARCHAR(512) NULL,
    token_count INT NULL,
    start_paragraph_id INT NULL,
    end_paragraph_id INT NULL,
    start_page_number INT NULL,
    end_page_number INT NULL,
    kept BOOLEAN NOT NULL DEFAULT FALSE,
    filter_reason VARCHAR(255) NULL,
    diagnostics TEXT NULL,
    chunk_text MEDIUMTEXT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_report_chunk_diagnostic_report_id FOREIGN KEY (report_id) REFERENCES report_document(id),
    KEY idx_report_chunk_diagnostic_report_id (report_id),
    KEY idx_report_chunk_diagnostic_kept (kept),
    KEY idx_report_chunk_diagnostic_chunk_uid (chunk_uid)
);

CREATE TABLE IF NOT EXISTS report_ingest_failure (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    filename VARCHAR(255) NULL,
    title VARCHAR(255) NULL,
    source VARCHAR(255) NULL,
    institution VARCHAR(255) NULL,
    stage VARCHAR(64) NOT NULL,
    error_message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    KEY idx_report_ingest_failure_stage (stage),
    KEY idx_report_ingest_failure_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS ingest_job (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_uid VARCHAR(64) NOT NULL,
    report_id BIGINT NULL,
    report_title_snapshot VARCHAR(255) NULL,
    title_search_key VARCHAR(255) NULL,
    source VARCHAR(255) NULL,
    institution VARCHAR(255) NULL,
    publish_date DATE NULL,
    original_filename VARCHAR(255) NULL,
    file_path VARCHAR(1024) NOT NULL,
    ocr_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    chunk_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    vector_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    ocr_attempt_count INT NOT NULL DEFAULT 0,
    chunk_attempt_count INT NOT NULL DEFAULT 0,
    vector_attempt_count INT NOT NULL DEFAULT 0,
    next_run_at TIMESTAMP NOT NULL,
    priority INT NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64) NULL,
    last_error_message VARCHAR(512) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE KEY uk_ingest_job_uid (job_uid),
    KEY idx_ingest_job_next_run_at (next_run_at),
    KEY idx_ingest_job_ocr_status (ocr_status),
    KEY idx_ingest_job_chunk_status (chunk_status),
    KEY idx_ingest_job_vector_status (vector_status),
    KEY idx_ingest_job_report_id (report_id),
    KEY idx_ingest_job_title_search_key (title_search_key)
);

CREATE TABLE IF NOT EXISTS report_ingest_stage_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_uid VARCHAR(64) NOT NULL,
    report_id BIGINT NULL,
    report_title_snapshot VARCHAR(255) NULL,
    title_search_key VARCHAR(255) NULL,
    stage VARCHAR(32) NOT NULL,
    attempt INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    model_name VARCHAR(128) NULL,
    input_size INT NULL,
    output_size INT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP NULL,
    duration_ms BIGINT NULL,
    error_code VARCHAR(64) NULL,
    error_message_short VARCHAR(512) NULL,
    trace_id VARCHAR(128) NULL,
    created_at TIMESTAMP NOT NULL,
    UNIQUE KEY uk_stage_event_job_stage_attempt (job_uid, stage, attempt),
    KEY idx_stage_event_report_id (report_id),
    KEY idx_stage_event_title_search_key (title_search_key),
    KEY idx_stage_event_stage_status (stage, status),
    KEY idx_stage_event_created_at (created_at)
);
